### ISSUE TITLE
VS Code Insiders isn't supported

### ISSUE THREAD

**Issue by brianary** [golf1052/code-sync#26]
VSCode version: 1.18.0-insider

CodeSync version: 2.4.0

CodeSync log:
```
settings.ts
	2017-10-06T21:34:38.555Z - Creating settings with internal settings.json path and external extensions.json path: C:\Users\brian\.vscode-insiders\extensions\golf1052.code-sync-2.4.0\settings.json, extensions.json.
helpers.ts
	2017-10-06T21:34:38.593Z - Error while executing isCodeOnPath()
	2017-10-06T21:34:38.593Z - Command: code.cmd --version
	2017-10-06T21:34:38.593Z - Exception:
	2017-10-06T21:34:38.593Z - 	Name: Error
	2017-10-06T21:34:38.593Z - 	Message: Command failed: code.cmd --version
'code.cmd' is not recognized as an internal or external command,
operable program or batch file.

	2017-10-06T21:34:38.593Z - 	Stacktrace: Error: Command failed: code.cmd --version
'code.cmd' is not recognized as an internal or external command,
operable program or batch file.

	at checkExecSyncError (child_process.js:493:13)
	at Object.execSync (child_process.js:533:13)
	at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:684:22)
	at Object.isCodeOnPath (C:\Users\brian\.vscode-insiders\extensions\golf1052.code-sync-2.4.0\out\src\helpers.js:115:33)
	at C:\Users\brian\.vscode-insiders\extensions\golf1052.code-sync-2.4.0\out\src\extension.js:21:48
	at Generator.next (<anonymous>)
	at C:\Users\brian\.vscode-insiders\extensions\golf1052.code-sync-2.4.0\out\src\extension.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\brian\.vscode-insiders\extensions\golf1052.code-sync-2.4.0\out\src\extension.js:3:12)
	at activate (C:\Users\brian\.vscode-insiders\extensions\golf1052.code-sync-2.4.0\out\src\extension.js:18:12)
	at Function.e._callActivateOptional (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:461761)
	at Function.e._callActivate (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:461506)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:460859
	at Object.m [as _notify] (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:50471)
	at Object.enter (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:54036)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:55864)
	2017-10-06T21:34:38.593Z - Defaulting to false
cs.ts
	2017-10-06T21:57:50.620Z - Checking settings
	2017-10-06T21:57:50.629Z - Setting external extensions path as C:\Users\brian\OneDrive\Apps\code-sync\extensions.json.
	2017-10-06T21:57:50.629Z - Done checking settings.
	2017-10-06T21:57:50.629Z - External sync directory: C:\Users\brian\OneDrive\Apps\code-sync
	2017-10-06T21:57:50.633Z - Importing settings
	2017-10-06T21:57:50.633Z - Failed to import settings. Could not find settings.json at C:\Users\brian\OneDrive\Apps\code-sync\settings.json. Giving up.
	2017-10-06T21:57:50.637Z - Importing keybindings
	2017-10-06T21:57:50.637Z - Failed to import keybindings. Could not find keybindings.json at C:\Users\brian\OneDrive\Apps\code-sync\keybindings.json. Giving up.
	2017-10-06T21:57:50.637Z - Importing snippets
	2017-10-06T21:57:50.637Z - Failed to import snippets. Could not find snippets directory at C:\Users\brian\OneDrive\Apps\code-sync\snippets. Giving up.
```

Issue: Error: **Code was not found on your path, CodeSync will be unable to import or export your extensions.**

It looks like the extension isn't falling back to looking for _C:\Program Files\Microsoft VS Code Insiders\bin\code-insiders.cmd_

**Comment by golf1052** [comment]
I've just pushed 2.5.0 which adds support for the insiders version. I didn't do too much testing but it looks like things work. Try it out and report back if things still aren't working. Thanks for the report!

**Comment by brianary** [comment]
Looks like it works! Thanks for the fix!
